# Generated by Django 4.2.11 on 2026-06-10 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other / Prefer not to say')], max_length=10)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('zh', 'Mandarin')], default='en', max_length=2)),
                ('group1', models.CharField(choices=[('intervention', 'Intervention'), ('control', 'Non-intervention')], max_length=20)),
                ('group2', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('group3', models.CharField(choices=[('high', 'High Stress'), ('low', 'Low Stress')], max_length=20)),
                ('adrd_relationship_group', models.CharField(choices=[('spouse', 'Spouse'), ('children', 'Children / Adult Child'), ('relative', 'Other Relative')], max_length=20)),
                ('stage', models.CharField(choices=[('early', 'Early'), ('middle', 'Middle'), ('late', 'Late')], max_length=20)),
                ('enrollment_week', models.PositiveSmallIntegerField(default=1)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('enrollment_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
