# Generated by Django 4.2.11 on 2026-06-14 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='label',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='stage',
        ),
    ]
