# Generated by Django 4.2.11 on 2026-07-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_remove_participant_label_remove_participant_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='adrd_stage',
            field=models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], help_text='Stage of ADRD of care recipient', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='label',
            field=models.CharField(blank=True, help_text='Short human-readable label e.g. Mrs. Smith', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
