# Generated by Django 4.2.11 on 2026-07-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_participant_adrd_stage_participant_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group1',
            field=models.CharField(choices=[('intervention', 'Intervention'), ('control', 'Control')], max_length=20),
        ),
    ]
