# Generated by Django 6.0.1 on 2026-08-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0004_participant_push_token_alter_participant_group1"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="cohort",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Recruitment cohort/wave number (e.g., 1 = Cohort 1, 2 = Cohort 2). Represents which recruitment area/wave the participant belongs to — independent of group1/group2/group3.",
            ),
        ),
    ]
