# Generated by Django 6.0.1 on 2026-08-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0005_participant_cohort"),
    ]

    operations = [
        migrations.CreateModel(
            name="CohortStartDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cohort",
                    models.PositiveSmallIntegerField(
                        help_text="Matches Participant.cohort", unique=True
                    ),
                ),
                (
                    "program_start_date",
                    models.DateField(
                        help_text="The date this cohort's Week 1 Day 1 content unlocks for everyone in it, regardless of individual signup date."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
