# Generated by Django 4.2.11 on 2026-09-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_cohortstartdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='group2',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], help_text='ADRD stage — may not be known at initial enrollment; can be filled in later.', max_length=20),
        ),
    ]
