# Generated by Django 4.2.11 on 2026-09-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_alter_participant_group2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='adrd_relationship_group',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('spouse', 'Spouse'), ('children', 'Children / Adult Child'), ('relative', 'Other Relative')], help_text='Caregiver relationship — may not be known at initial enrollment; can be filled in later.', max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group1',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('intervention', 'Intervention'), ('control', 'Control')], help_text='Study arm — may not be known at initial enrollment; can be filled in later.', max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group3',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('high', 'High Stress'), ('low', 'Low Stress')], help_text='Stress level — may not be known at initial enrollment; can be filled in later.', max_length=20),
        ),
    ]
