# Generated by Django 4.2.11 on 2026-09-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_alter_participant_adrd_relationship_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortstartdate',
            name='label',
            field=models.CharField(blank=True, help_text="Optional descriptive name, e.g. 'English speakers' or 'Wave 2 - Chinese'.", max_length=100),
        ),
    ]
