# Generated by Django 4.2.11 on 2026-09-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_cohortstartdate_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cohort',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Recruitment cohort/wave number (e.g., 1 = Cohort 1, 2 = Cohort 2). Represents which recruitment area/wave the participant belongs to — independent of group1/group2/group3. Left unset means "not yet assigned" — the cohort must exist (see Cohort Start Dates) before a participant can be put in it.', null=True),
        ),
    ]
