# Generated by Django 4.2.11 on 2026-06-10 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceJournalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(unique=True)),
                ('prompt_en', models.TextField()),
                ('prompt_zh', models.TextField()),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='VoiceJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('audio_s3_key', models.CharField(blank=True, max_length=500)),
                ('recording_seconds', models.PositiveIntegerField(default=0)),
                ('transcript', models.TextField(blank=True)),
                ('vj_stress_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('emotion_label', models.CharField(blank=True, choices=[('calm', 'Calm'), ('neutral', 'Neutral'), ('anxious', 'Anxious'), ('sad', 'Sad'), ('overwhelmed', 'Overwhelmed')], max_length=20)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='participants.participant')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('participant', 'week_number')},
            },
        ),
    ]
