# Generated by Django 4.2.11 on 2026-06-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicejournalentry',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='vj_recordings/'),
        ),
        migrations.AlterField(
            model_name='voicejournalentry',
            name='emotion_label',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('excited', 'Excited'), ('tired', 'Tired')], max_length=20),
        ),
    ]
