# Generated by Django 4.2.11 on 2026-06-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_voicejournalentry_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voicejournalentry',
            unique_together=set(),
        ),
    ]
