# Generated by Django 4.2.11 on 2026-06-10 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_zh', models.CharField(blank=True, max_length=200)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('day_number', models.PositiveSmallIntegerField()),
                ('video_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('text_content', models.TextField(blank=True)),
                ('text_content_zh', models.TextField(blank=True)),
                ('target_group1', models.CharField(blank=True, max_length=20)),
                ('target_group2', models.CharField(blank=True, max_length=20)),
                ('target_group3', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['week_number', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('daily', 'Daily Session'), ('unread_reminder', '24hr Unread Reminder'), ('vj_reminder', 'Voice Journal Reminder')], max_length=30)),
                ('push_up', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='participants.participant')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(blank=True, max_length=200)),
                ('week_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('video_open_count', models.PositiveIntegerField(default=0)),
                ('video_last_time', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('read_minutes', models.FloatField(default=0.0)),
                ('interactive_feature_count', models.PositiveIntegerField(default=0)),
                ('interactive_feature_comment', models.PositiveIntegerField(default=0)),
                ('infographic_open_count', models.PositiveIntegerField(default=0)),
                ('tracking_download_count', models.PositiveIntegerField(default=0)),
                ('pushup_time', models.DateTimeField(blank=True, null=True)),
                ('push_up', models.CharField(blank=True, max_length=200)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to='participants.participant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.session')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_zh', models.CharField(blank=True, max_length=200)),
                ('resource_type', models.CharField(choices=[('Video', 'Video'), ('Article', 'Article'), ('PDF', 'PDF')], max_length=20)),
                ('url', models.URLField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='content.session')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_states', to='participants.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.session')),
            ],
            options={
                'unique_together': {('participant', 'session')},
            },
        ),
    ]
