# Generated by Django 4.2.11 on 2026-06-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='session_audio/'),
        ),
        migrations.AddField(
            model_name='session',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='session_videos/'),
        ),
    ]
