# Generated by Django 4.2.11 on 2026-07-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_remove_participant_label_remove_participant_stage'),
        ('content', '0002_session_audio_file_session_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementlog',
            name='audio_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engagementlog',
            name='text_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engagementlog',
            name='video_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='engagementlog',
            unique_together={('participant', 'session')},
        ),
    ]
