# Generated by Django 4.2.11 on 2026-07-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_engagementlog_audio_time_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='target_group1',
            field=models.CharField(blank=True, choices=[('', 'All'), ('intervention', 'Intervention'), ('control', 'Control')], max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='target_group2',
            field=models.CharField(blank=True, choices=[('', 'All'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='target_group3',
            field=models.CharField(blank=True, choices=[('', 'All'), ('high', 'High Stress'), ('low', 'Low Stress')], max_length=20),
        ),
    ]
