# Generated by Django 4.2.11 on 2026-08-03 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_participant_push_token_alter_participant_group1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_alter_session_target_group1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('force_unlock', 'Force Unlock'), ('force_lock', 'Force Lock')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_overrides', to='participants.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='content.session')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('participant', 'session')},
            },
        ),
    ]
