# Generated by Django 4.2.11 on 2026-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_sessionoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped_no_token', 'Skipped — No Token')], default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('daily', 'Daily Session'), ('unread_reminder', '24hr Unread Reminder'), ('vj_reminder', 'Voice Journal Reminder'), ('manual', 'Manual / Ad-hoc')], max_length=30),
        ),
    ]
