# Generated by Django 4.2.11 on 2026-08-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_notificationlog_status_notificationlog_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='actually_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped_no_token', 'Skipped — No Token')], default='sent', max_length=20),
        ),
    ]
