# Generated by Django 6.0.1 on 2026-08-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_notificationlog_actually_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagementlog",
            name="video_watch_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Actual video playback time (from pressing play to pausing/stopping), as opposed to video_time_seconds which measures time the Video tab was simply active/visible.",
            ),
        ),
    ]
