# Generated by Django 6.0.1 on 2026-08-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_engagementlog_video_watch_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "send_time",
                    models.TimeField(
                        default="19:00",
                        help_text="Time of day (in the server's local timezone) the daily reminder is sent to all enrolled, non-waitlisted participants.",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Your session is ready!",
                        help_text="Notification title. Customizable by admin.",
                        max_length=200,
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        default="Come check out today's session in the WeCare app.",
                        help_text="Notification body text. Customizable by admin.",
                        max_length=200,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, no daily notifications will be sent, regardless of time.",
                    ),
                ),
                (
                    "last_sent_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the daily batch was last sent — used internally to prevent sending twice in the same day.",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
