# Generated by Django 4.2.11 on 2026-08-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_seed_dailynotificationsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailynotificationsettings',
            options={'verbose_name_plural': 'Daily notification settings'},
        ),
        migrations.AddField(
            model_name='participantsession',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Set the first time the participant opens this session, whether or not they finish it.', null=True),
        ),
        migrations.AlterField(
            model_name='participantsession',
            name='is_read',
            field=models.BooleanField(default=False, help_text='True once the participant has completed the session (spent meaningful time before leaving), not merely opened it.'),
        ),
    ]
