# Generated by Django 4.2.11 on 2026-08-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_dailynotificationsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='target_relationship',
            field=models.CharField(blank=True, choices=[('', 'All'), ('spouse', 'Spouse'), ('children', 'Children / Adult Child'), ('relative', 'Other Relative')], max_length=20),
        ),
    ]
