# Generated by Django 4.2.11 on 2026-08-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_session_target_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='text_content_html',
            field=models.TextField(blank=True, help_text="Rich HTML (headings, formatting, inline images hosted on S3) generated from an uploaded .docx via the admin's 'Upload Word document' field. Can be hand-edited afterward. Falls back to text_content on mobile when empty."),
        ),
        migrations.AddField(
            model_name='session',
            name='text_content_html_zh',
            field=models.TextField(blank=True, help_text='Chinese counterpart to text_content_html.'),
        ),
    ]
