# Generated by Django 4.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_session_text_content_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='text_content_pdf_url',
            field=models.URLField(blank=True, help_text="If set (via the admin's 'Upload PDF for Text section' field), the app shows an in-app PDF viewer for the Text tab instead of text_content_html."),
        ),
        migrations.AddField(
            model_name='session',
            name='text_content_pdf_url_zh',
            field=models.URLField(blank=True, help_text='Chinese counterpart to text_content_pdf_url.'),
        ),
    ]
