# Generated by Django 4.2.11 on 2026-09-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_session_text_content_pdf_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementlog',
            name='audio_time_seconds',
        ),
        migrations.RemoveField(
            model_name='session',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='session',
            name='audio_url',
        ),
    ]
