# Generated by Django 4.2.11 on 2026-09-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_remove_engagementlog_audio_time_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='video_url_zh',
            field=models.URLField(blank=True, help_text='Chinese counterpart to video_url.'),
        ),
    ]
