# Generated by Django 4.2.11 on 2026-09-08 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_session_video_url_zh'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('Video', 'Video'), ('PDF', 'PDF'), ('Audio', 'Audio')], max_length=20)),
                ('file_url', models.URLField(blank=True, help_text='Set automatically from the upload above.')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='additionalresource',
            name='media_asset',
            field=models.ForeignKey(blank=True, help_text='Pick an already-uploaded file from the library instead of re-uploading. Takes priority over URL above when set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
        migrations.AddField(
            model_name='session',
            name='text_pdf_asset',
            field=models.ForeignKey(blank=True, help_text='Pick an already-uploaded PDF from the library instead of re-uploading. Takes priority over Text PDF URL above when set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
        migrations.AddField(
            model_name='session',
            name='text_pdf_asset_zh',
            field=models.ForeignKey(blank=True, help_text='Chinese counterpart to Text PDF Asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
        migrations.AddField(
            model_name='session',
            name='video_asset',
            field=models.ForeignKey(blank=True, help_text='Pick an already-uploaded video from the library instead of re-uploading. Takes priority over Video URL above when set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
        migrations.AddField(
            model_name='session',
            name='video_asset_zh',
            field=models.ForeignKey(blank=True, help_text='Chinese counterpart to Video Asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
    ]
