# Generated by Django 4.2.11 on 2026-09-08 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_mediaasset_additionalresource_media_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='html_content',
            field=models.TextField(blank=True, help_text='Sanitized HTML, populated only for Document-type assets — converted from the uploaded .docx once, at upload time.'),
        ),
        migrations.AddField(
            model_name='session',
            name='docx_asset',
            field=models.ForeignKey(blank=True, help_text='Pick an already-uploaded Word document from the library — copies its HTML into Text Content HTML below once, at save time (still freely hand-editable afterward, same as a fresh .docx upload).', limit_choices_to={'asset_type': 'Document'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
        migrations.AddField(
            model_name='session',
            name='docx_asset_zh',
            field=models.ForeignKey(blank=True, help_text='Chinese counterpart to Word Document Asset.', limit_choices_to={'asset_type': 'Document'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='asset_type',
            field=models.CharField(choices=[('Video', 'Video'), ('PDF', 'PDF'), ('Audio', 'Audio'), ('Document', 'Document')], max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='text_content_html',
            field=models.TextField(blank=True, help_text="Rich HTML (headings, formatting, inline images hosted on S3) generated from an uploaded .docx (or picked Media Library document) via the admin's 'Upload Word document' field. Can be hand-edited afterward. Falls back to text_content on mobile when empty."),
        ),
        migrations.AlterField(
            model_name='session',
            name='text_pdf_asset',
            field=models.ForeignKey(blank=True, help_text='Pick an already-uploaded PDF from the library instead of re-uploading. Takes priority over Text PDF URL above when set.', limit_choices_to={'asset_type': 'PDF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
        migrations.AlterField(
            model_name='session',
            name='text_pdf_asset_zh',
            field=models.ForeignKey(blank=True, help_text='Chinese counterpart to Text PDF Asset.', limit_choices_to={'asset_type': 'PDF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
        migrations.AlterField(
            model_name='session',
            name='video_asset',
            field=models.ForeignKey(blank=True, help_text='Pick an already-uploaded video from the library instead of re-uploading. Takes priority over Video URL above when set.', limit_choices_to={'asset_type': 'Video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
        migrations.AlterField(
            model_name='session',
            name='video_asset_zh',
            field=models.ForeignKey(blank=True, help_text='Chinese counterpart to Video Asset.', limit_choices_to={'asset_type': 'Video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
    ]
