# Generated by Django 4.2.11 on 2026-09-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_mediaasset_html_content_session_docx_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='asset_type',
            field=models.CharField(choices=[('Video', 'Video'), ('PDF', 'PDF'), ('Audio', 'Audio'), ('Document', 'Document'), ('Image', 'Image')], max_length=20),
        ),
    ]
